{% set version = "2.0.0-19" %}
{% set name = "giac" %}

package:
  name: {{ name }}
  version: {{ version.replace('-', '.') }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/cxzhong/giac-feedstock/releases/download/v{{ version }}/{{ name }}_{{ version }}.tar.gz
  sha256: edfb8a57cc4d943c8df616b5f8d34752314f8443f4359ded8704572f591c0391
  patches:
    - 0003-giac-builds-against-libintl-on-macOS-even-with-GUI-d.patch
    - 0005-Enable-pari-factorization-in-macOS.patch
    - 0006-Fix-conda-relocation.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libtool
    - automake
    - gettext-tools
    - xz-tools
    - sed
    - make
    - flex
    - bison
  host:
    - libblas
    - libcblas
    - liblapack
    - readline
    - gmp
    - mpfr
    - mpfi
    - ntl
    - gf2x
    - gsl
    - pari
    - libpng
    - zlib
    - gettext   # [osx]
    - ncurses
    - ecm
    - glpk
    - libcurl
    - nauty
  run:
    - readline
    - gmp
    - mpfr
    - mpfi
    - ntl
    - gf2x
    - {{ pin_compatible('gsl', max_pin='x.x') }}
    - {{ pin_compatible('pari') }}
    - libpng
    - zlib
    - gettext   # [osx]
    - ncurses
    - {{ pin_compatible('ecm') }}
    - {{ pin_compatible('glpk') }}
    - {{ pin_compatible('nauty', max_pin='x') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]
    - giac 1

about:
  home: http://www-fourier.ujf-grenoble.fr/~parisse/giac.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Giac/Xcas is a free computer algebra system

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
