{% set version = "1.9.0-21" %}
{% set name = "giac" %}

package:
  name: {{ name }}
  version: {{ version.replace('-', '.') }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: http://www-fourier.ujf-grenoble.fr/~parisse/debian/dists/stable/main/source/{{ name }}_{{ version }}.tar.gz
  sha256: 120cd16f2e033817302d2a03a22bd413dc1d85df8b225ba4f76b93a7805b07fe
  patches:
    - 0001-Fix-compilation-without-GUI.patch
    - 0002-Do-not-use-clock_gettime.patch
    - 0003-giac-builds-against-libintl-on-macOS-even-with-GUI-d.patch
    - 0004-Adapt-to-changes-in-pari-2.15.patch
    # Patches taken from github.com/sagemath/sage
    # enable pari factorization in macos. this reverts the disabling in upstream
    # Reason for disabling was an interruptions problem when linking guis with
    # the macos binaries provided by upstream. Can't reproduce
    - patches/macos-ifactor.patch
    - patches/conda-relocation.diff

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libtool
    - automake
    - sed
    - make
    - flex
    - bison
  host:
    - libblas
    - libcblas
    - liblapack
    - readline
    - gmp
    - mpfr
    - mpfi
    - ntl
    - gf2x
    - gsl
    - pari
    - libpng
    - zlib
    - gettext   # [osx]
    - ncurses
    - ecm
    - glpk
    - libcurl
    - nauty
  run:
    - readline
    - gmp
    - mpfr
    - mpfi
    - ntl
    - gf2x
    - {{ pin_compatible('gsl', max_pin='x.x') }}
    - {{ pin_compatible('pari') }}
    - libpng
    - zlib
    - gettext   # [osx]
    - ncurses
    - {{ pin_compatible('ecm') }}
    - {{ pin_compatible('glpk') }}
    - {{ pin_compatible('nauty', max_pin='x') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]
    - giac 1

about:
  home: http://www-fourier.ujf-grenoble.fr/~parisse/giac.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Giac/Xcas is a free computer algebra system

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
