{% set version = "1.4.9-57" %}
{% set name = "giac" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version.replace('-', '.') }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: http://www-fourier.ujf-grenoble.fr/~parisse/debian/dists/stable/main/source/{{ name }}_{{ version }}.tar.gz
  sha256: 4d288d49b9f44a6060eb6a7cb6b86debe4ab572d6ff80060ad80ec27a831d162
  patches:
    # Patches taken from github.com/sagemath/sage
    # enable pari factorization in macos. this reverts the disabling in upstream
    # Reason for disabling was an interruptions problem when linking guis with
    # the macos binaries provided by upstream. Can't reproduce
    - patches/macos-ifactor.patch

build:
  number: 2
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - automake

  host:
    - readline 6.2*
    - gmp
    - mpfr
    - mpfi
    - ntl
    - gsl
    - pari
    - blas 1.1 {{ variant }}
    - openblas
    - libpng

  run:
    - {{ pin_compatible('readline') }}
    - gmp
    - mpfr
    - mpfi
    - ntl
    - {{ pin_compatible('gsl', max_pin='x.x') }}
    - {{ pin_compatible('pari') }}
    - blas 1.1 {{ variant }}
    - openblas
    - libpng

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://www-fourier.ujf-grenoble.fr/~parisse/giac.html
  license: GPL v3+
  license_file: COPYING
  summary: Giac/Xcas is a free computer algebra system

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
